spring:
  shardingsphere:
    mode:
      # 内存模式 元数据存储方式：内存，单机Standalone，集群Cluster
      type: Memory
    props:
      # 打印sql
      sql-show: true
    datasource:
      # 配置数据源，名字与下面对应
      names: order0
      # 配置写数据源
      order0:
        type: com.zaxxer.hikari.HikariDataSource
        driver: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3314/sharding_sphere?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: root
        password: 123456
    rules:
      encrypt:
        encryptors:
          aes_encryptor:
            type: AES
            props:
              aes-key-value: 123456abc
          md5_encryptor:
            type: MD5
        tables:
          t_order:
            columns:
              phone:
                plainColumn: phone
                cipherColumn: phone_cipher
                encryptorName: aes_encryptor
                #
                #assistedQueryColumn: phone_assisted_query
                #assistedQueryEncryptorName: md5_encryptor
            query-with-cipher-column: false