spring:
  shardingsphere:
    mode:
      # 内存模式 元数据存储方式：内存，单机Standalone，集群Cluster
      type: Memory
    props:
      # 打印sql
      sql-show: true
    datasource:
      # 配置数据源，名字与下面对应
      names: order0,shadow0
      # 配置写数据源
      order0:
        type: com.zaxxer.hikari.HikariDataSource
        driver: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3312/sharding_sphere?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: root
        password: 123456
      shadow0:
        type: com.zaxxer.hikari.HikariDataSource
        driver: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3315/sharding_sphere?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: root
        password: 123456
    rules:
      shadow:
        enable: true
        dataSources:
          shadowDataSource:
            sourceDataSourceName: order0
            shadowDataSourceName: shadow0
        shadowAlgorithms:
          user-id-insert-match-algorithm:
            # 基于列的影子算法仅支持部分 SQL。
            # 如果type为VALUE_MATCH，则regex改为value 对应的值也需要修改
            type: REGEX_MATCH
            props:
              operation: insert
              column: user_id
              regex: "\\d+"
          user-id-update-match-algorithm:
            type: REGEX_MATCH
            props:
              operation: update
              column: user_id
              regex: "\\d+"
          user-id-select-match-algorithm:
            type: REGEX_MATCH
            props:
              operation: select
              column: user_id
              regex: "\\d+"
          simple-hint-algorithm:
            # 基于Hint 的影子算法支持全部 SQL
            type: SIMPLE_HINT
            props:
              shadow: true
        tables:
          t_order:
            dataSourceNames:
              - shadowDataSource
            shadowAlgorithmNames:
              - user-id-insert-match-algorithm
              - simple-hint-algorithm
              - user-id-select-match-algorithm
              - user-id-update-match-algorithm