spring:
  shardingsphere:
    mode:
      # 内存模式 元数据存储方式：内存，单机Standalone，集群Cluster
      type: Memory
    props:
      # 打印sql
      sql-show: true
    datasource:
      # 配置数据源，名字与下面对应
      names: user,order
      # 配置写数据源
      user:
        type: com.zaxxer.hikari.HikariDataSource
        driver: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3311/sharding_sphere?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      order:
        type: com.zaxxer.hikari.HikariDataSource
        driver: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3310/sharding_sphere?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    rules:
      sharding:
        tables:
          t_user:
            actual-data-nodes: user.t_user
          t_order:
            actual-data-nodes: order.t_order
