spring:
  shardingsphere:
    mode:
      # 内存模式 元数据存储方式：内存，单机Standalone，集群Cluster
      type: Memory
    props:
      # 打印sql
      sql-show: true
    datasource:
      # 配置数据源，名字与下面对应
      names: order
      # 配置写数据源
      order:
        type: com.zaxxer.hikari.HikariDataSource
        driver: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3310/sharding_sphere?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: root
        password: 123456
    rules:
      sharding:
        tables:
          t_order:
            actual-data-nodes: order.t_order$->{0..1}
            table-strategy:
              standard:
                sharding-column: order_no
                sharding-algorithm-name: alg_hash_mod
        sharding-algorithms:
          alg_hash_mod:
            type: HASH_MOD
            props:
              sharding-count: 2
